version: '3.8'
services:
  golang:
    restart: always
    command: go run main.go
  postgres:
    volumes:
      - postgresvolume:/var/lib/postgresql/data
  node:
    environment:
      - NODE_ENV=production
    command: npm start
volumes:
  postgresvolume:
