version: '3.8'
services:
  golang:
    environment:
      - CGO_ENABLED=0
    command: go test -v
  postgres:
    volumes:
      - postgrestestvolume:/var/lib/postgresql/data/test
    environment:
      PGDATA: /var/lib/postgresql/data/test
  node:
    environment:
      - NODE_ENV=testing
    command: npm test
volumes:
  postgrestestvolume:
