version: '3.8'
services:
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379

  golang:
    image: golang:1.15-alpine
    volumes:
      - ./go:/go/src/go
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=
    working_dir: /go/src/go
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - redis

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  node:
    image: node:12-alpine
    user: node
    working_dir: /home/node/app
    restart: on-failure
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - REDIS_HOST=redis
    volumes:
      - ./node:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
